### ISSUE TITLE
Installation not falling back to IPv4 in case IPv6 is broken on yunohost servers.

### ISSUE THREAD

**Issue by gl** [YunoHost/install_script#14]
The following command blocks the install if repo.yunohost.org is unreachable in IPv6 and the server yunohost is being installed on has IPv6 enabled.

wget -O- http://repo.yunohost.org/yunohost.asc -q | apt-key add - -qq

This happened to me when "repo.yunohost.org" IPv6 was broken and I had proper IPv6 connectivity. By removing the IPv6 on the target VM, I was able to Retry the command and carry on with the installation.

I suppose the wget available during installation is not falling back by itself (normal wget will fallback).

Options:
0) Fix the IPv6 on the servers and monitor it properly
0-evil) Remove the IPv6 from the DNS for the yunohost servers
1) change the wget so that it will fallback
2) do wget -6 and if it fails do wget -4 and if it fails bring an error
3) certainly a lot of other options, like not using wget

**Comment by julienmalik** [comment]
option 0 now implemented :)
