### ISSUE TITLE
New installation from Debian failed

### ISSUE THREAD

**Issue by solarus0** [YunoHost/install_script#19]
Hello. I tried to install Yunohost from a brand new Debian Wheezy server.
But the installation script failed and i've got these error message

The installer need the package "ssowat" but can't found it. I don't understand why.

Here is the error message :
root@c1-10-1-12-112:~# cd /tmp/install_script && sudo ./install_yunohostv2
======== Get path of current script =======
Running from /tmp/install_script
======== Check rights ========
======== YunoHost Installation ========
======== Check dependencies ========
======== Checking domain ========
======== Adding repositories ========
OK
======== Install ========
======== Installation failed ========
Rolling back have to be done manually !
Check your legacy configuration files => '/etc/yunohost/.legacy'
Check install logs => '/var/log/yunohost.log' and '/var/log/yunohost.error'
root@c1-10-1-12-112:/tmp/install_script# more /var/log/yunohost.log
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 yunohost-config : Depends: ssowat but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by tomgue** [comment]
La même chose sur un ubuntu 14.10 clean

```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 yunohost-config : Depends: acpi-support-base but it is not installable
                   Depends: haste but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by Kloadut** [comment]
@tomgue YunoHost est pour le moment compatible uniquement avec Debian 7.

**Comment by tomgue** [comment]
@Kloadut ah donc voila pourquoi... le support d'ubuntu est planifier ?

**Comment by Kloadut** [comment]
@tomgue Hélas, c'est trop compliqué pour nous de maintenir plusieurs distribs, donc non, pas au programme :)

**Comment by beyerservice** [comment]
good to know!
would be cool if it is writen in RED lettern on yunohost.org :-)
I missed that badly :-(

**Comment by julienmalik** [comment]
old issue, old install script version. closing...
