### ISSUE TITLE
"PHP Startup: Unable to load dynamic library" errors in admin user's mailbox

### ISSUE THREAD

**Issue by michielbdejong** [YunoHost/install_script#23]
I set up Yunohost using this install script, and created a user on there. This user now has a lot of mails in his yunohost mail with the message:

"PHP Warning:  PHP Startup: Unable to load dynamic library
'/usr/lib/php5/20100525/php_mbstring.dll' -
/usr/lib/php5/20100525/php_mbstring.dll: cannot open shared object file:
No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library
'/usr/lib/php5/20100525/php_exif.dll' -
/usr/lib/php5/20100525/php_exif.dll: cannot open shared object file: No
such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library
'/usr/lib/php5/20100525/php_gd2.dll' -
/usr/lib/php5/20100525/php_gd2.dll: cannot open shared object file: No
such file or directory in Unknown on line 0".mail 

Is that something to worry about? Can it be avoided?

**Comment by julienmalik** [comment]
What applications are deployed on the server ?

**Comment by julienmalik** [comment]
Does grep-ing for say "php_exif" in /etc/php5 returns something ?

**Comment by michielbdejong** [comment]
It looks like php_exif is not there:
````
root@mydomain:~# grep -r php_exif /etc/php5
root@mydomain:~# ls /etc/php5/
cli/            conf.d/         fpm/            mods-available/ 
root@mydomain:~# ls /etc/php5/fpm/
conf.d/       php-fpm.conf  php.ini       pool.d/       
root@mydomain:~# ls /etc/php5/fpm/conf.d/
10-pdo.ini  20-curl.ini  20-gd.ini  20-imap.ini  20-intl.ini  20-ldap.ini  20-mcrypt.ini  20-mysql.ini	20-mysqli.ini  20-pdo_mysql.ini
root@mydomain:~# ls /etc/php5/cli/conf.d/
10-pdo.ini  20-curl.ini  20-gd.ini  20-imap.ini  20-intl.ini  20-ldap.ini  20-mcrypt.ini  20-mysql.ini	20-mysqli.ini  20-pdo_mysql.ini
root@mydomain:~# ls /etc/php5/conf.d/
10-pdo.ini  20-curl.ini  20-gd.ini  20-imap.ini  20-intl.ini  20-ldap.ini  20-mcrypt.ini  20-mysql.ini	20-mysqli.ini  20-pdo_mysql.ini
root@mydomain:~# ls /etc/php5/mods-available/
curl.ini  gd.ini  imap.ini  intl.ini  ldap.ini	mcrypt.ini  mysql.ini  mysqli.ini  pdo.ini  pdo_mysql.ini
root@mydomain:~# 
````

Can't check right now which apps are installed (I have root access, but I don't have a Yunohost account on this server), but at least mail and lychee, and probably some others as well.

It looks like [lychee uses exif](https://github.com/titoko/lychee_ynh/search?utf8=%E2%9C%93&q=exif), so that's probably the culprit then...

Will open a ticket there, thanks for the debugging hints!
