### ISSUE TITLE
Install fails on a fresh Debian 7

### ISSUE THREAD

**Issue by src386** [YunoHost/install_script#26]
Hi everyone,

the install_script fails to install Yunohost in a fresh Debian installation : 

    Les paquets suivants contiennent des dépendances non satisfaites :
     yunohost-config : Dépend: yunohost-admin mais ne sera pas installé
                       Dépend: moulinette mais ne sera pas installé
                       Dépend: moulinette-yunohost mais ne sera pas installé
    E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».

Here is the issue with moulinette : 

    moulinette : Dépend: python-bottle (>= 0.12) mais ne sera pas installé

python-bottle already exists in Debian Wheezy : 

    python-bottle  0.10.11-1+de all

Python-bottle 0.12 exists in yunohost repo but for an unknown reason, apt do not want to use it.

Work arround : 

    wget http://repo.yunohost.org/pool/main/p/python-bottle/python-bottle_0.12.7-1~bpo70%2b1_all.deb
    dpkg -i python-bottle_0.12.7-1~bpo70%2b1_all.deb
    ./install_yunohostv2

Regards.

Xavier C.

**Comment by Kloadut** [comment]
Should be fixed by now, just added `python-bottle` 0.12 to the new stable repo
