### ISSUE TITLE
NTP synchronisation problem

### ISSUE THREAD

**Issue by solarus0** [YunoHost/install_script#28]
Hello everyone.
I have checked the ntpd service on my Yunohost server and it does'nt work.

root@vps50776:~# ntpq -p
ntpq: read: Connection refused

The daemon has a problem and can't run normally.
Can you check on your own servers and tell me if you can reproduce this bug.

Thanks a lot.

**Comment by M5oul** [comment]
It works for me.

**Comment by solarus0** [comment]
Thank for your anwser.

Actually it's not related to Yunohost.
It's caused by my VPS (OVH) based on OpenVZ. The hypervisor controls the time system and sets the clock for all the VM.
The VM can't access the kernel function about time and date.

I close this issue.
