### ISSUE TITLE
Make the install script scriptable

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost/install_script#9]
With something like : 

--domain
--admin-password
--quiet
--force

**Comment by julienmalik** [comment]
Started in #32 with automatic install and YunoHost distrib choice.
I support the idea of --domain && --admin-password

**Comment by julienmalik** [comment]
Now it has a "-a" for automatic install.
Still missing --domain et --admin-password.

**Comment by julienmalik** [comment]
See https://dev.yunohost.org/issues/51
